insert into mail_template_master(id, product_id, service_category, communication_category, mail_subject, mail_body, send_from_mail_address)
values(1, 1, '見積', '承認依頼', '【' || CHR(123) || CHR(123) || 'replaceValue1' || CHR(125) || CHR(125) || '】見積承認依頼メール',  CHR(123) || CHR(123) || 'replaceValue1' || CHR(125) || CHR(125) || ' さん' || CHR(10) || CHR(10) || '見積番号' || CHR(123) || CHR(123) || 'replaceValue2' || CHR(125) || CHR(125) || 'の見積承認を依頼されました。下記リンクから確認してください。' || CHR(10) || CHR(123) || CHR(123) || 'replaceValue3' || CHR(125) || CHR(125) || CHR(10) || CHR(10) || '送信専用アドレスから送信しています。返信しないでください。', 'oshirase_shindenryoku@example.com');
insert into mail_template_master(id, product_id, service_category, communication_category, mail_subject, mail_body, send_from_mail_address)
values(2, 1, '見積', '承認', '【' || CHR(123) || CHR(123) || 'replaceValue1' || CHR(125) || CHR(125) || '】見積承認完了メール',  CHR(123) || CHR(123) || 'replaceValue1' || CHR(125) || CHR(125) || ' さん' || CHR(10) || CHR(10) || '見積番号' || CHR(123) || CHR(123) || 'replaceValue2' || CHR(125) || CHR(125) || 'の見積承認が完了しました。下記リンクから確認してください。' || CHR(10) || CHR(123) || CHR(123) || 'replaceValue3' || CHR(125) || CHR(125) || CHR(10) || CHR(10) || '送信専用アドレスから送信しています。返信しないでください。', 'oshirase_shindenryoku@example.com');
insert into mail_template_master(id, product_id, service_category, communication_category, mail_subject, mail_body, send_from_mail_address)
values(3, 1, '見積', '承認依頼差戻', '【' || CHR(123) || CHR(123) || 'replaceValue1' || CHR(125) || CHR(125) || '】見積承認依頼差戻メール',  CHR(123) || CHR(123) || 'replaceValue1' || CHR(125) || CHR(125) || ' さん' || CHR(10) || CHR(10) || '見積番号' || CHR(123) || CHR(123) || 'replaceValue2' || CHR(125) || CHR(125) || 'の見積承認依頼が差し戻されました。下記リンクから確認してください。' || CHR(10) || CHR(123) || CHR(123) || 'replaceValue3' || CHR(125) || CHR(125) || CHR(10) || CHR(10) || '送信専用アドレスから送信しています。返信しないでください。', 'oshirase_shindenryoku@example.com');
insert into mail_template_master(id, product_id, service_category, communication_category, mail_subject, mail_body, send_from_mail_address)
values(4, 1, '契約', '承認依頼', '【' || CHR(123) || CHR(123) || 'replaceValue1' || CHR(125) || CHR(125) || '】契約承認依頼メール',  CHR(123) || CHR(123) || 'replaceValue1' || CHR(125) || CHR(125) || ' さん' || CHR(10) || CHR(10) || '見積番号' || CHR(123) || CHR(123) || 'replaceValue2' || CHR(125) || CHR(125) || 'の契約承認を依頼されました。下記リンクから確認してください。' || CHR(10) || CHR(123) || CHR(123) || 'replaceValue3' || CHR(125) || CHR(125) || CHR(10) || CHR(10) || '送信専用アドレスから送信しています。返信しないでください。', 'oshirase_shindenryoku@example.com');
insert into mail_template_master(id, product_id, service_category, communication_category, mail_subject, mail_body, send_from_mail_address)
values(5, 1, '契約', '承認', '【' || CHR(123) || CHR(123) || 'replaceValue1' || CHR(125) || CHR(125) || '】契約承認完了メール',  CHR(123) || CHR(123) || 'replaceValue1' || CHR(125) || CHR(125) || ' さん' || CHR(10) || CHR(10) || '見積番号' || CHR(123) || CHR(123) || 'replaceValue2' || CHR(125) || CHR(125) || 'の契約承認が完了しました。下記リンクから確認してください。' || CHR(10) || CHR(123) || CHR(123) || 'replaceValue3' || CHR(125) || CHR(125) || CHR(10) || CHR(10) || '送信専用アドレスから送信しています。返信しないでください。', 'oshirase_shindenryoku@example.com');
insert into mail_template_master(id, product_id, service_category, communication_category, mail_subject, mail_body, send_from_mail_address)
values(6, 1, '契約', '承認依頼差戻', '【' || CHR(123) || CHR(123) || 'replaceValue1' || CHR(125) || CHR(125) || '】契約承認依頼差戻メール',  CHR(123) || CHR(123) || 'replaceValue1' || CHR(125) || CHR(125) || ' さん' || CHR(10) || CHR(10) || '見積番号' || CHR(123) || CHR(123) || 'replaceValue2' || CHR(125) || CHR(125) || 'の契約承認依頼が差し戻されました。下記リンクから確認してください。' || CHR(10) || CHR(123) || CHR(123) || 'replaceValue3' || CHR(125) || CHR(125) || CHR(10) || CHR(10) || '送信専用アドレスから送信しています。返信しないでください。', 'oshirase_shindenryoku@example.com');
insert into mail_template_master(id, product_id, service_category, communication_category, mail_subject, mail_body, send_from_mail_address)
values(7, 1, '手配', '作業依頼', '【' || CHR(123) || CHR(123) || 'replaceValue1' || CHR(125) || CHR(125) || '】手配作業依頼メール',  CHR(123) || CHR(123) || 'replaceValue1' || CHR(125) || CHR(125) || ' さん' || CHR(10) || CHR(10) || '見積番号' || CHR(123) || CHR(123) || 'replaceValue2' || CHR(125) || CHR(125) || 'の手配作業を依頼されました。下記リンクから確認してください。' || CHR(10) || CHR(123) || CHR(123) || 'replaceValue3' || CHR(125) || CHR(125) || CHR(10) || CHR(10) || '送信専用アドレスから送信しています。返信しないでください。', 'oshirase_shindenryoku@example.com');
insert into mail_template_master(id, product_id, service_category, communication_category, mail_subject, mail_body, send_from_mail_address)
values(8, 1, '手配', '作業完了', '【' || CHR(123) || CHR(123) || 'replaceValue1' || CHR(125) || CHR(125) || '】手配作業完了メール',  CHR(123) || CHR(123) || 'replaceValue1' || CHR(125) || CHR(125) || ' さん' || CHR(10) || CHR(10) || '見積番号' || CHR(123) || CHR(123) || 'replaceValue2' || CHR(125) || CHR(125) || 'の手配作業が完了しました。下記リンクから確認してください。' || CHR(10) || CHR(123) || CHR(123) || 'replaceValue3' || CHR(125) || CHR(125) || CHR(10) || CHR(10) || '送信専用アドレスから送信しています。返信しないでください。', 'oshirase_shindenryoku@example.com');
insert into mail_template_master(id, product_id, service_category, communication_category, mail_subject, mail_body, send_from_mail_address)
values(9, 1, '手配', '作業依頼差戻', '【' || CHR(123) || CHR(123) || 'replaceValue1' || CHR(125) || CHR(125) || '】手配作業依頼差メール',  CHR(123) || CHR(123) || 'replaceValue1' || CHR(125) || CHR(125) || ' さん' || CHR(10) || CHR(10) || '見積番号' || CHR(123) || CHR(123) || 'replaceValue2' || CHR(125) || CHR(125) || 'の手配作業依頼が差し戻されました。下記リンクから確認してください。' || CHR(10) || CHR(123) || CHR(123) || 'replaceValue3' || CHR(125) || CHR(125) || CHR(10) || CHR(10) || '送信専用アドレスから送信しています。返信しないでください。', 'oshirase_shindenryoku@example.com');
