INSERT INTO AUTH_PATTERN_MASTER (AUTH_PATTERN_ID,ACTION_DIV,AUTH_DIV,ACCESS_TYPE,VERSION)
  VALUES (1,'01','2200','参照',1);
INSERT INTO DISP_URL_AUTH_MASTER (SYSTEM_DOMAIN,URL_PATTERN,ACTION_ID,ACTION_NAME,AUTH_PATTERN_ID,VERSION)
  VALUES ('cotos.ricoh.co.jp','api/estimation/[0-9]+','TEST_ACTION_001','登録ボタン',1,1);
INSERT INTO DISP_URL_AUTH_MASTER (SYSTEM_DOMAIN,URL_PATTERN,ACTION_ID,ACTION_NAME,AUTH_PATTERN_ID,VERSION)
  VALUES ('cotos.ricoh.co.jp','api/estimation/[0-9]+','TEST_ACTION_002','承認ボタン',1,1);