insert into employee_con(id,created_at,created_user,deleted_at,deleted_user,updated_at,updated_user,version,address,employee_name,fax_number,mail_address,mom_employee_id,mom_org_id,org_hierarchy_level,org_name,phone_number,sales_company_name,sales_department_name,post_number,org_phone_number)
values(1,null,null,null,null,null,null,0,'東京都港区芝浦３丁目４－１グランパークタワー田町ビル','床嶋邦臣',null,'dummy@nts.ricoh.co.jp','01196146','0913299',4,'販売事業本部　ＨＥ事業部　大学営業部　第三担当室　',null,'Ｒジャパン（東京）','第三担当室（大学）','1080023','03-6830-9980');
insert into employee_con(id,created_at,created_user,deleted_at,deleted_user,updated_at,updated_user,version,address,employee_name,fax_number,mail_address,mom_employee_id,mom_org_id,org_hierarchy_level,org_name,phone_number,sales_company_name,sales_department_name,post_number,org_phone_number)
values(2,null,null,null,null,null,null,0,'北海道札幌市中央区北七条西１３丁目９－１塚本ビル７号館　４Ｆ','玉村淳一',null,'zpg_jpi_st_mail01@nts.ricoh.co.jp','00229692','0913430',4,'販売事業本部　北海道支社　札幌南西営業部　南西第一営業所　',null,'Ｒジャパン（北海道）','南西第一営業所','0600007','050-3534-4277');
insert into employee_con(id,created_at,created_user,deleted_at,deleted_user,updated_at,updated_user,version,address,employee_name,fax_number,mail_address,mom_employee_id,mom_org_id,org_hierarchy_level,org_name,phone_number,sales_company_name,sales_department_name,post_number,org_phone_number)
values(3,null,null,null,null,null,null,0,'北海道札幌市中央区北七条西１３丁目９－１塚本ビル７号館　４Ｆ','大浦康彦',null,'zpg_jpi_st_mail01@nts.ricoh.co.jp','00623643','0913430',4,'販売事業本部　北海道支社　札幌南西営業部　南西第一営業所　',null,'Ｒジャパン（北海道）','南西第一営業所','0600007','050-3534-4277');
insert into employee_con(id,created_at,created_user,deleted_at,deleted_user,updated_at,updated_user,version,address,employee_name,fax_number,mail_address,mom_employee_id,mom_org_id,org_hierarchy_level,org_name,phone_number,sales_company_name,sales_department_name,post_number,org_phone_number)
values(4,null,null,null,null,null,null,0,'北海道札幌市中央区北七条西１３丁目９－１塚本ビル７号館　４Ｆ','外角直紀',null,'zpg_jpi_st_mail01@nts.ricoh.co.jp','00548632','0913922',4,'販売事業本部　北海道支社　札幌南西営業部　南西第一営業所　',null,'Ｒジャパン（北海道）','南西第一営業所','0600007','050-3534-4277');
insert into employee_con(id,created_at,created_user,deleted_at,deleted_user,updated_at,updated_user,version,address,employee_name,fax_number,mail_address,mom_employee_id,mom_org_id,org_hierarchy_level,org_name,phone_number,sales_company_name,sales_department_name,post_number,org_phone_number)
values(5,null,null,null,null,null,null,0,'北海道札幌市中央区北七条西１３丁目９－１塚本ビル７号館　４Ｆ','渡辺陽三',null,'zpg_jpi_st_mail01@nts.ricoh.co.jp','00611619','0913922',4,'販売事業本部　北海道支社　札幌南西営業部　南西第一営業所　',null,'Ｒジャパン（北海道）','南西第一営業所','0600007','050-3534-4277');
