SELECT
 ORG_ID AS RESULT
FROM
 MV_WJMOB820_ORG_HIERARCHY_COM
WHERE
 ORG_HIERARCHY_LEVEL_KBN = '10'
 AND ORG_ID IN (select org_id from V_PIC_AFFILIATE_MASTER_FULL start with ORG_ID = :orgId CONNECT BY PRIOR ORG_ID = HIGH_ORG_ID)