DELETE FROM DISP_URL_AUTH_MASTER;
DELETE FROM AUTH_PATTERN_MASTER;
DELETE FROM JWT_SYS_AUTH_MASTER;
DELETE FROM ESTIMATION_ATTACHED_FILE;
DELETE FROM OPERATION_LOG;


DELETE FROM ESTIMATION;

DELETE FROM COMMON_MASTER_DETAIL;
DELETE FROM COMMON_MASTER;